scrape_configs:
  - job_name: ticket-submitter
    kubernetes_sd_configs:
      - role: pod
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_label_app]
        regex: ticket-submitter
        action: keep
  - job_name: mongodb
    kubernetes_sd_configs:
      - role: pod
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_label_app]
        regex: mongodb
        action: keep
